deploy_dev:
  stage: deploy
  script:
    - chmod +x mvnw
    - ./mvnw -Dmaven.test.skip=true clean package
    - sudo sh /home/ubuntu/docker/deploy.sh member 9000
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: manual
  tags:
    - deploy-dev