deploy_dev:
  stage: deploy
  script:
    - chmod +x mvnw
    - ./mvnw -Dmaven.test.skip=true -Pdev clean package
    - sudo sh ../deploy/member.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: manual
  tags:
    - deploy-dev