-- SSP 기초 데이터 --
INSERT INTO SSP_ERROR_CODE (ID, CODE, REASON, STATUS, IS_TRACE) VALUES ('SSP.AUTHENTICATION.401', 'E00401', '유효하지 않은 토큰입니다.', 401, 'N');
INSERT INTO SSP_ERROR_CODE (ID, CODE, REASON, STATUS, IS_TRACE) VALUES ('SSP.AUTHENTICATION.403', 'E00403', 'API 사용 권한이 없습니다.', 403, 'N');
INSERT INTO SSP_ERROR_CODE (ID, CODE, REASON, STATUS, IS_TRACE) VALUES ('BOOTSTRAP.TODO.MODIFY.400', 'E01400', '존재하지 않는 id입니다.', 400, 'N');

INSERT INTO SSP_MEMBER_GROUP_MAPPED (UID, GROUP_ID) VALUES ('U00000', 'G00000');
INSERT INTO SSP_MEMBER_GROUP_MAPPED (UID, GROUP_ID) VALUES ('U10001', 'G00001');
INSERT INTO SSP_MEMBER_GROUP_MAPPED (UID, GROUP_ID) VALUES ('U10002', 'G00002');
INSERT INTO SSP_MEMBER_GROUP_MAPPED (UID, GROUP_ID) VALUES ('U00001', 'G00003');
INSERT INTO SSP_MEMBER_GROUP_MAPPED (UID, GROUP_ID) VALUES ('U00002', 'G00003');
INSERT INTO SSP_MEMBER_GROUP_MAPPED (UID, GROUP_ID) VALUES ('U00003', 'G00004');
INSERT INTO SSP_MEMBER_GROUP_MAPPED (UID, GROUP_ID) VALUES ('U00004', 'G00004');
INSERT INTO SSP_MEMBER_GROUP_MAPPED (UID, GROUP_ID) VALUES ('U00005', 'G00004');

INSERT INTO SSP_GROUP_ROLE_MAPPED (GROUP_ID, ROLE_ID) VALUES ('G00000', 'R00000');
INSERT INTO SSP_GROUP_ROLE_MAPPED (GROUP_ID, ROLE_ID) VALUES ('G00001', 'R00001');
INSERT INTO SSP_GROUP_ROLE_MAPPED (GROUP_ID, ROLE_ID) VALUES ('G00001', 'R00002');
INSERT INTO SSP_GROUP_ROLE_MAPPED (GROUP_ID, ROLE_ID) VALUES ('G00001', 'R00003');
INSERT INTO SSP_GROUP_ROLE_MAPPED (GROUP_ID, ROLE_ID) VALUES ('G00001', 'R00004');
INSERT INTO SSP_GROUP_ROLE_MAPPED (GROUP_ID, ROLE_ID) VALUES ('G00002', 'R00001');
INSERT INTO SSP_GROUP_ROLE_MAPPED (GROUP_ID, ROLE_ID) VALUES ('G00002', 'R00002');
INSERT INTO SSP_GROUP_ROLE_MAPPED (GROUP_ID, ROLE_ID) VALUES ('G00002', 'R00003');
INSERT INTO SSP_GROUP_ROLE_MAPPED (GROUP_ID, ROLE_ID) VALUES ('G00003', 'R00001');
INSERT INTO SSP_GROUP_ROLE_MAPPED (GROUP_ID, ROLE_ID) VALUES ('G00003', 'R00002');
INSERT INTO SSP_GROUP_ROLE_MAPPED (GROUP_ID, ROLE_ID) VALUES ('G00004', 'R00001');

INSERT INTO SSP_ROLE_API_MAPPED (ROLE_ID, API_ID) VALUES ('R00000', 'A00000'); -- all
INSERT INTO SSP_ROLE_API_MAPPED (ROLE_ID, API_ID) VALUES ('R00001', 'A00001'); -- 내부 API - 읽기
INSERT INTO SSP_ROLE_API_MAPPED (ROLE_ID, API_ID) VALUES ('R00001', 'A00004'); -- 내부 API - 읽기
INSERT INTO SSP_ROLE_API_MAPPED (ROLE_ID, API_ID) VALUES ('R00002', 'A00002'); -- 내부 API - 등록/수정/삭제
INSERT INTO SSP_ROLE_API_MAPPED (ROLE_ID, API_ID) VALUES ('R00002', 'A00003'); -- 내부 API - 등록/수정/삭제
INSERT INTO SSP_ROLE_API_MAPPED (ROLE_ID, API_ID) VALUES ('R00002', 'A00005'); -- 내부 API - 등록/수정/삭제
INSERT INTO SSP_ROLE_API_MAPPED (ROLE_ID, API_ID) VALUES ('R00003', 'A00007'); -- 외부 API - 조회전용
INSERT INTO SSP_ROLE_API_MAPPED (ROLE_ID, API_ID) VALUES ('R00004', 'A00006'); -- 외부 API - 수정 및 ASYNC
INSERT INTO SSP_ROLE_API_MAPPED (ROLE_ID, API_ID) VALUES ('R00004', 'A00008'); -- 외부 API - 수정 및 ASYNC
INSERT INTO SSP_ROLE_API_MAPPED (ROLE_ID, API_ID) VALUES ('R00004', 'A00009'); -- 외부 API - 수정 및 ASYNC
INSERT INTO SSP_ROLE_API_MAPPED (ROLE_ID, API_ID) VALUES ('R00004', 'A00010'); -- 외부 API - 수정 및 ASYNC

INSERT INTO SSP_API_INFO (API_ID, SERVICE_NAME, HOST, API, METHOD, API_DESC) VALUES ('A00000', 'ssp-bootstrap', 'http://localhost:9000', '/apis/**', '', '전체');
INSERT INTO SSP_API_INFO (API_ID, SERVICE_NAME, HOST, API, METHOD, API_DESC) VALUES ('A00001', 'ssp-bootstrap', 'http://localhost:9000', '/apis/todos', 'GET', 'TODO 전체 조회');
INSERT INTO SSP_API_INFO (API_ID, SERVICE_NAME, HOST, API, METHOD, API_DESC) VALUES ('A00002', 'ssp-bootstrap', 'http://localhost:9000', '/apis/todos', 'POST', 'TODO 등록');
INSERT INTO SSP_API_INFO (API_ID, SERVICE_NAME, HOST, API, METHOD, API_DESC) VALUES ('A00003', 'ssp-bootstrap', 'http://localhost:9000', '/apis/todos/{id}', 'PUT', 'TODO 수정');
INSERT INTO SSP_API_INFO (API_ID, SERVICE_NAME, HOST, API, METHOD, API_DESC) VALUES ('A00004', 'ssp-bootstrap', 'http://localhost:9000', '/apis/todos/{id}', 'GET', 'TODO 조회');
INSERT INTO SSP_API_INFO (API_ID, SERVICE_NAME, HOST, API, METHOD, API_DESC) VALUES ('A00005', 'ssp-bootstrap', 'http://localhost:9000', '/apis/todos/{id}', 'DELETE', 'TODO 삭제');
INSERT INTO SSP_API_INFO (API_ID, SERVICE_NAME, HOST, API, METHOD, API_DESC) VALUES ('A00007', 'ssp-bootstrap', 'http://localhost:9000', '/apis/todos/external/{id}', 'GET', 'TODO 조회 - 외부 API 호출');

INSERT INTO SSP_ROUTING_SERVICE_INFO (SERVICE_NAME, HOST, SERVICE_DESC) VALUES ('USER', 'http://localhost:9010', '사용자 서비스');
INSERT INTO SSP_ROUTING_SERVICE_INFO (SERVICE_NAME, HOST, SERVICE_DESC) VALUES ('APIS', 'http://localhost:9000', 'API 서비스');
